[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  base = "packages/joobs-web"
  publish = "dist/"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"

# [dev]
#   command = "pnpm dev"
