/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/jobs": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.jobs.id"];
          job_offer_id?: parameters["rowFilter.jobs.job_offer_id"];
          job_offer_title?: parameters["rowFilter.jobs.job_offer_title"];
          job_offer_name?: parameters["rowFilter.jobs.job_offer_name"];
          job_offer_photo1?: parameters["rowFilter.jobs.job_offer_photo1"];
          job_offer_photo2?: parameters["rowFilter.jobs.job_offer_photo2"];
          job_offer_photo3?: parameters["rowFilter.jobs.job_offer_photo3"];
          job_offer_detail?: parameters["rowFilter.jobs.job_offer_detail"];
          job_offer_area?: parameters["rowFilter.jobs.job_offer_area"];
          job_offer_salary_range?: parameters["rowFilter.jobs.job_offer_salary_range"];
          job_offer_skill_name?: parameters["rowFilter.jobs.job_offer_skill_name"];
          job_offer_new_flg?: parameters["rowFilter.jobs.job_offer_new_flg"];
          job_offer_updated_at_timestamp?: parameters["rowFilter.jobs.job_offer_updated_at_timestamp"];
          btn_type?: parameters["rowFilter.jobs.btn_type"];
          btn_state?: parameters["rowFilter.jobs.btn_state"];
          other_job_offers?: parameters["rowFilter.jobs.other_job_offers"];
          created_at?: parameters["rowFilter.jobs.created_at"];
          updated_at?: parameters["rowFilter.jobs.updated_at"];
          client_id?: parameters["rowFilter.jobs.client_id"];
          client_name?: parameters["rowFilter.jobs.client_name"];
          client_title?: parameters["rowFilter.jobs.client_title"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["jobs"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** jobs */
          jobs?: definitions["jobs"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.jobs.id"];
          job_offer_id?: parameters["rowFilter.jobs.job_offer_id"];
          job_offer_title?: parameters["rowFilter.jobs.job_offer_title"];
          job_offer_name?: parameters["rowFilter.jobs.job_offer_name"];
          job_offer_photo1?: parameters["rowFilter.jobs.job_offer_photo1"];
          job_offer_photo2?: parameters["rowFilter.jobs.job_offer_photo2"];
          job_offer_photo3?: parameters["rowFilter.jobs.job_offer_photo3"];
          job_offer_detail?: parameters["rowFilter.jobs.job_offer_detail"];
          job_offer_area?: parameters["rowFilter.jobs.job_offer_area"];
          job_offer_salary_range?: parameters["rowFilter.jobs.job_offer_salary_range"];
          job_offer_skill_name?: parameters["rowFilter.jobs.job_offer_skill_name"];
          job_offer_new_flg?: parameters["rowFilter.jobs.job_offer_new_flg"];
          job_offer_updated_at_timestamp?: parameters["rowFilter.jobs.job_offer_updated_at_timestamp"];
          btn_type?: parameters["rowFilter.jobs.btn_type"];
          btn_state?: parameters["rowFilter.jobs.btn_state"];
          other_job_offers?: parameters["rowFilter.jobs.other_job_offers"];
          created_at?: parameters["rowFilter.jobs.created_at"];
          updated_at?: parameters["rowFilter.jobs.updated_at"];
          client_id?: parameters["rowFilter.jobs.client_id"];
          client_name?: parameters["rowFilter.jobs.client_name"];
          client_title?: parameters["rowFilter.jobs.client_title"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.jobs.id"];
          job_offer_id?: parameters["rowFilter.jobs.job_offer_id"];
          job_offer_title?: parameters["rowFilter.jobs.job_offer_title"];
          job_offer_name?: parameters["rowFilter.jobs.job_offer_name"];
          job_offer_photo1?: parameters["rowFilter.jobs.job_offer_photo1"];
          job_offer_photo2?: parameters["rowFilter.jobs.job_offer_photo2"];
          job_offer_photo3?: parameters["rowFilter.jobs.job_offer_photo3"];
          job_offer_detail?: parameters["rowFilter.jobs.job_offer_detail"];
          job_offer_area?: parameters["rowFilter.jobs.job_offer_area"];
          job_offer_salary_range?: parameters["rowFilter.jobs.job_offer_salary_range"];
          job_offer_skill_name?: parameters["rowFilter.jobs.job_offer_skill_name"];
          job_offer_new_flg?: parameters["rowFilter.jobs.job_offer_new_flg"];
          job_offer_updated_at_timestamp?: parameters["rowFilter.jobs.job_offer_updated_at_timestamp"];
          btn_type?: parameters["rowFilter.jobs.btn_type"];
          btn_state?: parameters["rowFilter.jobs.btn_state"];
          other_job_offers?: parameters["rowFilter.jobs.other_job_offers"];
          created_at?: parameters["rowFilter.jobs.created_at"];
          updated_at?: parameters["rowFilter.jobs.updated_at"];
          client_id?: parameters["rowFilter.jobs.client_id"];
          client_name?: parameters["rowFilter.jobs.client_name"];
          client_title?: parameters["rowFilter.jobs.client_title"];
        };
        body: {
          /** jobs */
          jobs?: definitions["jobs"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  jobs: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    job_offer_id?: number;
    job_offer_title?: string;
    job_offer_name?: string;
    job_offer_photo1?: string;
    job_offer_photo2?: string;
    job_offer_photo3?: string;
    job_offer_detail?: string;
    job_offer_area?: string;
    job_offer_salary_range?: string;
    job_offer_skill_name?: string;
    job_offer_new_flg?: boolean;
    job_offer_updated_at_timestamp?: string;
    btn_type?: string;
    btn_state?: boolean;
    other_job_offers?: string;
    created_at?: string;
    updated_at?: string;
    client_id?: number;
    client_name?: string;
    client_title?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** jobs */
  "body.jobs": definitions["jobs"];
  "rowFilter.jobs.id": string;
  "rowFilter.jobs.job_offer_id": string;
  "rowFilter.jobs.job_offer_title": string;
  "rowFilter.jobs.job_offer_name": string;
  "rowFilter.jobs.job_offer_photo1": string;
  "rowFilter.jobs.job_offer_photo2": string;
  "rowFilter.jobs.job_offer_photo3": string;
  "rowFilter.jobs.job_offer_detail": string;
  "rowFilter.jobs.job_offer_area": string;
  "rowFilter.jobs.job_offer_salary_range": string;
  "rowFilter.jobs.job_offer_skill_name": string;
  "rowFilter.jobs.job_offer_new_flg": string;
  "rowFilter.jobs.job_offer_updated_at_timestamp": string;
  "rowFilter.jobs.btn_type": string;
  "rowFilter.jobs.btn_state": string;
  "rowFilter.jobs.other_job_offers": string;
  "rowFilter.jobs.created_at": string;
  "rowFilter.jobs.updated_at": string;
  "rowFilter.jobs.client_id": string;
  "rowFilter.jobs.client_name": string;
  "rowFilter.jobs.client_title": string;
}

export interface operations {}

export interface external {}
